ldap_authentication_conf:
  sids:
    ldap_server: ldap_server
  authenticationMode: 1
  loginUIUsernameTxt: null
  loginUIPasswordTxt: null
  ldapUserHelpLinkUrl: null
  ldapUserHelpLinkText: 'Logon Help'
  emailOption: 3
  emailUpdate: 1
  passwordOption: 2
  allowOnlyIfTextInDn: {  }
  excludeIfTextInDn: {  }
  allowTestPhp: ''
  excludeIfNoAuthorizations: null
  ssoRemoteUserStripDomainName: null
  ssoExcludedPaths: {  }
  ssoExcludedHosts: {  }
  seamlessLogin: null
  ldapImplementation: null
  cookieExpire: null
_core:
  default_config_hash: 535558b922f833a593a144524aa814f6
langcode: fr
