ldap_servers.settings:
  type: mapping
  label: Settings
  mapping:
    ldap_servers_encryption:
      type: boolean
      label: 'Require HTTPS on credential pages'
    ldap_servers_encrypt_key:
      type: boolean
    ldap_servers_require_ssl_for_credentails:
      type: integer
